from pathlib import Path

path = Path('app_ui.py')
text = path.read_text(encoding='utf-8')

old = '''    selected_label = st.pills(\n        "Disease context",\n        context_options,\n        default="All GBM literature",\n        selection_mode="single",\n        key=f"literature_context_{gene}",\n    ) or "All GBM literature"\n    context_key = label_to_key.get(selected_label)\n\n    applied_key = f"literature_applied_terms_{gene}"\n    with st.form(f"literature_search_form_{gene}", clear_on_submit=False):\n        search_text = st.text_input(\n            "Search publications",\n            value=st.session_state.get(applied_key, ""),\n            placeholder="e.g. osimertinib, CAR T, resistance, extracellular vesicles",\n            help="Searches within this gene's GBM literature in Europe PMC.",\n        )\n        search_col, clear_col = st.columns([1, 1])\n        with search_col:\n            search_submitted = st.form_submit_button("Search", type="primary", width="stretch")\n        with clear_col:\n            clear_submitted = st.form_submit_button("Clear search", width="stretch")\n    if search_submitted:\n        st.session_state[applied_key] = search_text.strip()\n    elif clear_submitted:\n        st.session_state[applied_key] = ""\n    applied_terms = st.session_state.get(applied_key, "")\n'''

new = '''    applied_key = f"literature_applied_terms_{gene}"\n    search_input_key = f"literature_search_input_{gene}"\n    st.session_state.setdefault(applied_key, "")\n    st.session_state.setdefault(search_input_key, st.session_state[applied_key])\n\n    def clear_literature_search() -> None:\n        st.session_state[applied_key] = ""\n        st.session_state[search_input_key] = ""\n\n    selected_label = st.pills(\n        "Disease context",\n        context_options,\n        default="All GBM literature",\n        selection_mode="single",\n        key=f"literature_context_{gene}",\n        on_change=clear_literature_search,\n    ) or "All GBM literature"\n    context_key = label_to_key.get(selected_label)\n\n    with st.form(f"literature_search_form_{gene}", clear_on_submit=False):\n        search_text = st.text_input(\n            "Search publications",\n            key=search_input_key,\n            placeholder="e.g. osimertinib, CAR T, resistance, extracellular vesicles",\n            help="Searches within this gene's GBM literature in Europe PMC.",\n        )\n        search_col, clear_col = st.columns([1, 1])\n        with search_col:\n            search_submitted = st.form_submit_button("Search", type="primary", width="stretch")\n        with clear_col:\n            st.form_submit_button(\n                "Clear search",\n                width="stretch",\n                on_click=clear_literature_search,\n            )\n    if search_submitted:\n        st.session_state[applied_key] = search_text.strip()\n    applied_terms = st.session_state.get(applied_key, "")\n'''

if old not in text:
    raise SystemExit('Expected publication filter block not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
print('PUBLICATION_FILTER_STATE_REFINED')
